export const FETCH_PROPERTIES_SUCCESS = 'FETCH_PROPERTIES_SUCCESS';
export const FETCH_PROPERTIES_REQUEST = 'FETCH_PROPERTIES_REQUEST';
export const FETCH_PROPERTIES_FAILURE = 'FETCH_PROPERTIES_FAILURE';
export const UPDATE_LOCATION_NAME = 'UPDATE_LOCATION_NAME';
export const PROPERTY_REQUEST = 'PROPERTY_REQUEST';
export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
